"""The dashboard's bundled desired state equals a fresh generation: python3 -m unittest discover -s .github/scripts

dashboard/worker/src/drift-desired.json is generated by drift_desired.py from every production config, every
deploy-vars wrapper and the list of hand-set secret names. This test regenerates it and compares, so a config or
wrapper change cannot leave the dashboard's drift check comparing the live account with an old desired state.
Fix a failure with `python3 .github/scripts/drift_desired.py` (Python 3.11+, Node.js) and commit the JSON.

Like test_wrangler_configs.py it needs Python 3.11+ (tomllib) and is skipped with a message on an older python3
outside GitHub Actions; it also needs Node.js to import the JavaScript wrappers (always present on the runner).
"""

import json
import os
import shutil
import sys
import unittest

if sys.version_info < (3, 11) and os.environ.get("GITHUB_ACTIONS") != "true":
    raise unittest.SkipTest(
        f"test_drift_desired needs Python 3.11+ (tomllib), this is {sys.version.split()[0]}: "
        "uv run --no-project --python 3.12 python -m unittest discover -s .github/scripts"
    )
if shutil.which("node") is None and os.environ.get("GITHUB_ACTIONS") != "true":
    raise unittest.SkipTest("test_drift_desired needs Node.js to import the JavaScript deploy-vars wrappers")

import drift_desired  # noqa: E402
from test_wrangler_configs import PRODUCTION  # noqa: E402

# What the JSON may contain: names, flags and the config paths. Never an id, an address or a value.
FORBIDDEN = ("@", "database_id", "account_id", "cloudflareaccess.com")


class DesiredState(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.generated = drift_desired.render(drift_desired.build())
        cls.state = json.loads(cls.generated)

    def test_the_committed_json_is_a_fresh_generation(self):
        committed = drift_desired.OUTPUT.read_text() if drift_desired.OUTPUT.exists() else ""
        self.assertEqual(
            committed,
            self.generated,
            "dashboard/worker/src/drift-desired.json is out of date: run python3 .github/scripts/drift_desired.py",
        )

    def test_it_covers_exactly_the_production_workers(self):
        self.assertEqual(drift_desired.WORKERS, PRODUCTION)
        self.assertEqual(set(self.state["workers"]), set(PRODUCTION))

    def test_it_holds_names_only(self):
        for text in FORBIDDEN:
            with self.subTest(text=text):
                self.assertNotIn(text, self.generated)
        for worker, desired in self.state["workers"].items():
            for binding in desired["bindings"]:
                with self.subTest(worker=worker, binding=binding["name"]):
                    self.assertLessEqual(set(binding), {"name", "type", "source", "optional"})
                    self.assertIn(binding["source"], {"config", "deploy", "manual"})

    def test_every_wrapper_value_and_manual_secret_is_listed(self):
        """The deploy values (vars and secrets) and the hand-set secrets of each Worker appear with their types."""
        home = {b["name"]: b for b in self.state["workers"]["home"]["bindings"]}
        self.assertEqual(home["CF_ANALYTICS_TOKEN"], {"name": "CF_ANALYTICS_TOKEN", "type": "secret_text", "source": "deploy"})
        self.assertEqual(home["BUILD_SHA"]["type"], "plain_text")
        for worker, names in drift_desired.MANUAL_SECRETS.items():
            bindings = {b["name"]: b for b in self.state["workers"][worker]["bindings"]}
            for name in names:
                with self.subTest(worker=worker, name=name):
                    self.assertEqual(bindings[name]["type"], "secret_text")
                    self.assertEqual(bindings[name]["source"], "manual")

    def test_personal_values_are_named_for_the_secret_check(self):
        """A personal wrapper value sent with --var would be listed under `personal`; every wrapper now writes its
        personal values with --secrets-file, so no Worker lists one (each is a secret_text deploy binding instead)."""
        personal = {worker: set(desired["personal"]) for worker, desired in self.state["workers"].items()}
        for worker, names in personal.items():
            bindings = {b["name"] for b in self.state["workers"][worker]["bindings"]}
            with self.subTest(worker=worker):
                self.assertLessEqual(names, bindings)
                self.assertEqual(names, set())

    def test_todofy_personal_values_are_deploy_secrets(self):
        """Todofy writes the core's Todoist projects and the gateway's owner addresses with --secrets-file, one file per
        Worker; an unset optional project is uploaded too (as unset), so every one is a required secret_text binding.
        The vars it adds are the switches and BUILD_SHA."""
        workers = {
            "todofy-core": ("TODOIST_DEFAULT_PROJECT_ID", "TODOIST_OPS_PROJECT_ID", "TODOIST_REVIEW_PROJECT_ID"),
            "todofy": ("ACCESS_OWNER", "ACCESS_OWNER_ALIASES"),
        }
        switches = {
            "todofy-core": ("BUILD_SHA", "MAINTENANCE_MODE", "REMINDER_ENABLED", "PROCESSING_PAUSED", "FORCE_PAUSE_TODOIST", "GTD_REVIEW_ENABLED"),
            "todofy": ("BUILD_SHA", "MAINTENANCE_MODE"),
        }
        for worker, names in workers.items():
            bindings = {b["name"]: b for b in self.state["workers"][worker]["bindings"]}
            for name in names:
                with self.subTest(worker=worker, name=name):
                    self.assertEqual(bindings[name], {"name": name, "type": "secret_text", "source": "deploy"})
            for name in switches[worker]:
                with self.subTest(worker=worker, name=name):
                    self.assertEqual(bindings[name], {"name": name, "type": "plain_text", "source": "deploy"})
            deployed = {name for name, binding in bindings.items() if binding["source"] == "deploy"}
            self.assertEqual(deployed, set(names) | set(switches[worker]))

    def test_mail_hero_personal_values_are_deploy_secrets(self):
        """Mail Hero writes its receive address and owner addresses with --secrets-file (as the dashboard and Lab
        write theirs), so they are wanted as secret_text bindings; the vars it adds are the switches and BUILD_SHA."""
        worker = self.state["workers"]["mail-hero"]
        bindings = {b["name"]: b for b in worker["bindings"]}
        for name in ("RECEIVE_ADDRESS", "ACCESS_OWNER", "ACCESS_OWNER_ALIASES"):
            with self.subTest(name=name):
                self.assertEqual(bindings[name], {"name": name, "type": "secret_text", "source": "deploy"})
        for name in ("FORCE_SEND_PAUSED", "MAINTENANCE_MODE", "BUILD_SHA"):
            with self.subTest(name=name):
                self.assertEqual(bindings[name], {"name": name, "type": "plain_text", "source": "deploy"})
        self.assertEqual(worker["personal"], [])

    def test_flowday_secrets_all_come_from_its_deploy(self):
        """FlowDay's wrapper writes the owner addresses, the CSRF key and the credential key (it seals the Todoist key in
        D1) with --secrets-file and adds BUILD_SHA as a var; no secret is set by hand. Its one hostname is the staging
        Custom Domain (F3) until the F4 cutover."""
        worker = self.state["workers"]["flowday"]
        bindings = {b["name"]: b for b in worker["bindings"]}
        secrets = ("ACCESS_OWNER", "ACCESS_OWNER_ALIASES", "CSRF_SIGNING_KEY", "CREDENTIAL_KEY")
        for name in secrets:
            with self.subTest(name=name):
                self.assertEqual(bindings[name], {"name": name, "type": "secret_text", "source": "deploy"})
        self.assertEqual(bindings["BUILD_SHA"], {"name": "BUILD_SHA", "type": "plain_text", "source": "deploy"})
        self.assertEqual({name for name, b in bindings.items() if b["source"] == "deploy"}, {*secrets, "BUILD_SHA"})
        self.assertEqual({name for name, b in bindings.items() if b["source"] == "manual"}, set())
        self.assertEqual(
            {(name, b["type"]) for name, b in bindings.items() if b["source"] == "config"},
            {
                ("ACCESS_AUDIENCE", "plain_text"),
                ("ACCESS_ISSUER", "plain_text"),
                ("ASSETS", "assets"),
                ("DB", "d1"),
                ("PUBLIC_HOST", "plain_text"),
            },
        )
        self.assertNotIn("flowday", drift_desired.MANUAL_SECRETS)
        self.assertEqual((worker["workers_dev"], worker["preview_urls"], worker["crons"]), (False, False, []))
        self.assertEqual(worker["custom_domains"], ["flowday-next.ziyixi.science"])
        self.assertEqual((worker["routes"], worker["personal"]), ([], []))

    def test_the_generator_refuses_an_unknown_binding_section(self):
        with self.assertRaises(drift_desired.GeneratorError):
            drift_desired.config_bindings("x", {"name": "x", "kv_namespaces": [{"binding": "KV"}]})

    def test_the_routes_are_in_a_known_zone(self):
        for worker, desired in self.state["workers"].items():
            for host in desired["custom_domains"]:
                with self.subTest(worker=worker, host=host):
                    self.assertTrue(any(host == zone or host.endswith("." + zone) for zone in self.state["zones"]))


if __name__ == "__main__":
    unittest.main()
