# Generated by tools/cloud-config/generate.py; public DNS identity only.
# Account credentials and private values remain sensitive Terraform variables.
locals {
  platform_zone_id          = "39163aaaa9eba38eca58f3ea969710bf"
  platform_zone             = "ziyixi.science"
  fleet_hostname            = "fleet.ziyixi.science"
  platform_runtime_hostname = "platform-runtime.ziyixi.science"
  platform_access_team      = "ziyixi"
}
