apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: personal-cloud
resources:
  - platform-runtime.yaml
  - deployment.yaml
  - config-sync.yaml
  - service.yaml
  - daily.yaml
  - release.yaml
  - observer.yaml
