// Generated by tools/cloud-config/generate.py; public repair links only.
export const ACTIONS_RECONCILE_URL = "https://github.com/ziyixi/todofy/actions/workflows/personal-cloud-reconcile.yml";
export const REBUILD_DOC_URL = "https://github.com/ziyixi/todofy/blob/main/docs/rebuild.md#host-recovery";
