"""Generates stdlib-only Python modules for the wire JSON profile from a buf image (proto/README.md).

Usage (tools/ensure.mjs runs it; never by hand)::

    buf build --exclude-imports --exclude-source-info -o -#format=json \
        | python3 tools/gen_py.py OUT_DIR

For every file of the module, ``todofy/taskintent/v1/task_intent.proto`` say, it writes
``OUT_DIR/todofy/taskintent/v1/task_intent_pb.py`` (plus an empty ``__init__.py`` in every directory):
one ``IntEnum`` per enum, one frozen dataclass per message and a ``FIELDS`` table that the hand-written
runtime ``ziyixi_proto.wire_json`` reads and writes. OUT_DIR is the ``ziyixi_proto`` package directory.

Why not protoc's Python output: todofy-core runs stdlib-only on Pyodide, and the contracts' wire format is
JSON, not protobuf binary. Only the field kinds the contracts use are supported; anything else stops
generation with an error, so a new kind cannot slip through. The output depends only on the image, so
generation is deterministic (the "Proto checks" CI job generates twice and compares).

Runs on Python 3.9 or newer (the system python3 of a developer machine); the generated code needs 3.12.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

PACKAGE = "ziyixi_proto"
HEADER = "# Generated by proto/tools/gen_py.py from proto/{source}. DO NOT EDIT; never committed.\n"
# protobuf type -> (Python annotation, default, wire_json kind)
SCALARS = {
    "TYPE_STRING": ("str", '""', "string"),
    "TYPE_BOOL": ("bool", "False", "bool"),
    "TYPE_INT32": ("int", "0", "int32"),
}
TIMESTAMP = ".google.protobuf.Timestamp"
REQUIRED_OPTION = "[google.api.field_behavior]"


class GenerateError(Exception):
    """The image uses something the wire profile does not support."""


def enum_prefix(name: str) -> str:
    """AIP-126 / buf ENUM_VALUE_PREFIX: ErrorCode -> ERROR_CODE_."""
    out = "".join(f"_{c}" if c.isupper() and i > 0 else c for i, c in enumerate(name))
    return out.upper() + "_"


def module_of(proto_path: str) -> str:
    """todofy/taskintent/v1/task_intent.proto -> todofy.taskintent.v1.task_intent_pb."""
    if not proto_path.endswith(".proto"):
        raise GenerateError(f"{proto_path}: not a .proto file")
    return proto_path[: -len(".proto")].replace("/", ".") + "_pb"


def index_types(image: dict[str, Any]) -> dict[str, tuple[str, str]]:
    """Full type name (".pkg.Name") -> (module, class name) for every top-level type of the image."""
    types: dict[str, tuple[str, str]] = {}
    for file in image["file"]:
        module = module_of(file["name"])
        for kind in ("enumType", "messageType"):
            for desc in file.get(kind, []):
                types[f".{file['package']}.{desc['name']}"] = (module, desc["name"])
    return types


def generate_file(file: dict[str, Any], types: dict[str, tuple[str, str]]) -> str:
    """The Python source of one .proto file."""
    module = module_of(file["name"])
    package = file["package"]
    imports: set[str] = set()
    body: list[str] = []
    tables: list[str] = []

    def ref(type_name: str, where: str) -> str:
        if type_name not in types:
            raise GenerateError(f"{where}: {type_name} is not in this module (only the profile's types are)")
        owner, name = types[type_name]
        if owner == module:
            return name
        alias = owner.replace(".", "_")
        imports.add(f"import {PACKAGE}.{owner} as {alias}")
        return f"{alias}.{name}"

    for enum_type in file.get("enumType", []):
        name, prefix = enum_type["name"], enum_prefix(enum_type["name"])
        values = enum_type["value"]
        if not values or values[0]["number"] != 0 or not values[0]["name"].endswith("_UNSPECIFIED"):
            raise GenerateError(f"{package}.{name}: the zero value must be *_UNSPECIFIED")
        body += ["", "", f"class {name}(enum.IntEnum):"]
        body += [f'    """{package}.{name}; wire names are lower case without {prefix}."""', ""]
        for value in values:
            if not value["name"].startswith(prefix):
                raise GenerateError(f"{package}.{name}.{value['name']} lacks the prefix {prefix}")
            body.append(f"    {value['name'][len(prefix) :]} = {value['number']}")

    for message in file.get("messageType", []):
        name = message["name"]
        if message.get("nestedType") or message.get("enumType"):
            raise GenerateError(f"{package}.{name}: nested types are not in the profile")
        # proto3 `optional` declares a synthetic oneof per field; a real oneof is not in the profile.
        if any("oneofIndex" in f and not f.get("proto3Optional") for f in message.get("field", [])):
            raise GenerateError(f"{package}.{name}: oneofs are not in the profile")
        body += ["", "", "@dataclasses.dataclass(frozen=True, slots=True, kw_only=True)", f"class {name}:"]
        body += [f'    """{package}.{name}."""', ""]
        fields: list[str] = []
        for field in sorted(message.get("field", []), key=lambda f: f["number"]):
            where = f"{package}.{name}.{field['name']}"
            repeated = field["label"] == "LABEL_REPEATED"
            optional = bool(field.get("proto3Optional", False))
            required = "REQUIRED" in field.get("options", {}).get(REQUIRED_OPTION, [])
            target = "None"
            if field["type"] in SCALARS:
                annotation, default, kind = SCALARS[field["type"]]
            elif field["type"] == "TYPE_ENUM":
                annotation = target = ref(field["typeName"], where)
                default, kind = f"{annotation}.UNSPECIFIED", "enum"
            elif field["type"] == "TYPE_MESSAGE" and field["typeName"] == TIMESTAMP:
                annotation, default, kind = "str", "None", "timestamp"
                optional = True  # a message field has explicit presence
            elif field["type"] == "TYPE_MESSAGE":
                annotation = target = ref(field["typeName"], where)
                default, kind = "None", "message"
                optional = True
            else:
                raise GenerateError(f"{where}: {field['type']} is not in the profile")
            if repeated:
                annotation, default = f"tuple[{annotation}, ...]", "()"
            elif optional:
                annotation, default = f"{annotation} | None", "None"
            body.append(f"    {field['name']}: {annotation} = {default}")
            fields.append(
                f"Field({json.dumps(field['name'])}, {field['number']}, {json.dumps(kind)}, {target}, "
                f"repeated={repeated}, optional={optional}, required={required})"
            )
        if not fields:
            body.append("    pass")
        tables.append(f"    {name}: (\n" + "".join(f"        {f},\n" for f in fields) + "    ),")

    lines = [
        HEADER.format(source=file["name"]).rstrip("\n"),
        f'"""{package} ({file["name"]}) in the wire JSON profile; read and write with {PACKAGE}.wire_json."""',
        "",
        "import dataclasses",
        "import enum",
        "",
        *sorted(imports),
        f"from {PACKAGE}.wire_json import Field",
        *body,
        "",
        "",
        "# Field tables of the wire JSON profile, in field-number order.",
        "FIELDS: dict[type, tuple[Field, ...]] = {",
        *tables,
        "}",
        "",
    ]
    return "\n".join(lines)


def generate(image: dict[str, Any]) -> dict[str, str]:
    """Relative output path -> source, for every file of the image and every package directory."""
    types = index_types(image)
    out: dict[str, str] = {}
    for file in sorted(image["file"], key=lambda f: f["name"]):
        if file.get("syntax") != "proto3":
            raise GenerateError(f"{file['name']}: only proto3 files are in the profile")
        module = module_of(file["name"])
        parts = module.split(".")
        for depth in range(1, len(parts)):
            out["/".join(parts[:depth]) + "/__init__.py"] = ""
        out["/".join(parts) + ".py"] = generate_file(file, types)
    return out


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print("usage: gen_py.py OUT_DIR < image.json", file=sys.stderr)
        return 2
    try:
        files = generate(json.load(sys.stdin))
    except GenerateError as error:
        print(f"gen_py: {error}", file=sys.stderr)
        return 1
    root = Path(argv[1])
    for path, source in files.items():
        target = root / path
        target.parent.mkdir(parents=True, exist_ok=True)
        with open(target, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(source)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
