"""Generates the TypeScript wire JSON types of the binding contracts from a buf image (proto/README.md).

Usage (tools/ensure.mjs runs it; never by hand)::

    buf build --exclude-imports --exclude-source-info -o -#format=json \\
        | python3 tools/gen_wire_ts.py OUT_DIR

For every file of WIRE_PACKAGES, ``ops/v1/ops.proto`` say, it writes ``OUT_DIR/ops/v1/ops_wire.ts``: the JSON a
producer of the contract writes, as types (no runtime code, so importing it costs a bundle nothing):

- each enum as the union of its wire names (``'info' | 'warning' | 'critical'``, the zero value never written);
- each message as an interface of its wire fields: snake_case names in field-number order, a REQUIRED field always
  there (``| null`` when it is declared ``optional``), any other field optional, a closed ``allowed`` list as a union
  of literals (an ``open`` one is a string: a consumer keeps a newer code as read), maps as records (with their
  required keys), lists as readonly arrays;
- each union (``(common.wire.v1.message).discriminator``) as the union of its variants, one per discriminator value
  (variants of the same shape share one member), with the fields each variant has and without the ones it never has,
  so ``if (d.state === 'delivered') d.delivered_at`` is a string;
- each service as the methods of a Workers service binding (``status(): Promise<OpsStatus>``, positional methods
  with their request's fields as parameters), for the caller's binding type and the entrypoint's ``implements``;
- and ``WireTypes`` entries (declaration merging with proto/ts/wire-json.ts), so ``toWire(OpsStatusSchema, m)`` is
  typed as an ``OpsStatus`` wherever the app imports this module.

The protobuf-es output (``ops_pb.ts``) stays the message type the codec reads into and writes from; these types are
the JSON on either side of it. Deterministic: the output depends only on the image.

Runs on Python 3.9 or newer, like gen_py.py.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

import wire_rules

HEADER = "// Generated by proto/tools/gen_wire_ts.py from proto/{source}. DO NOT EDIT; never committed.\n"
# The packages whose wire JSON crosses a Workers service binding as plain objects and whose apps type it: ops.v1
# (every app's Ops entrypoint and the dashboard). Others keep to the protobuf-es types.
WIRE_PACKAGES = ("ops.v1",)
SCALARS = {"TYPE_STRING": "string", "TYPE_BOOL": "boolean", "TYPE_INT32": "number", "TYPE_DOUBLE": "number"}
STRING_WKT = (".google.protobuf.Timestamp", ".google.protobuf.FieldMask")


class GenerateError(Exception):
    """The image uses something these types cannot say."""


def camel(name: str) -> str:
    """lower_snake_case -> lowerCamelCase, as protobuf-es names a field's local name or a method."""
    head, *rest = name.split("_")
    return head + "".join(part[:1].upper() + part[1:] for part in rest)


def lower_first(name: str) -> str:
    return name[:1].lower() + name[1:]


def literal_union(values: tuple[str, ...]) -> str:
    return " | ".join(json.dumps(v).replace('"', "'") for v in values)


class FileWriter:
    """The wire types of one .proto file."""

    def __init__(self, file: dict[str, Any], enums: dict[str, dict[str, Any]], names: dict[str, str]) -> None:
        self.file = file
        self.enums = enums
        self.names = names  # full type name -> TypeScript name, for this file's types
        self.package = file["package"]

    def type_name(self, full: str, where: str) -> str:
        if full not in self.names:
            raise GenerateError(f"{where}: {full} is not a type of this file (wire types are generated per file)")
        return self.names[full]

    def value_type(self, field: dict[str, Any], allowed: tuple[str, ...] | None, open_list: bool, where: str) -> str:
        """The type of one value: a field, a list item or a map value."""
        kind = field["type"]
        if kind == "TYPE_ENUM":
            if allowed is not None and not open_list:
                return literal_union(allowed)
            return self.type_name(field["typeName"], where)
        if kind == "TYPE_MESSAGE":
            if field["typeName"] in STRING_WKT:
                return "string"
            return self.type_name(field["typeName"], where)
        if kind not in SCALARS:
            raise GenerateError(f"{where}: {kind} is not in the wire profile")
        if kind == "TYPE_STRING" and allowed is not None and not open_list:
            return literal_union(allowed)
        return SCALARS[kind]

    def member(self, view: wire_rules.FieldView, message: str) -> str | None:
        """One property of an interface or variant, or None when the variant never has the field."""
        field = view.field
        where = f"{self.package}.{message}.{field['name']}"
        rules = view.rules
        open_list = bool(rules and rules.open)
        required = wire_rules.required(field)
        # A REQUIRED field is always written, as null when it has no value. Only a field declared `optional` lacks
        # one on purpose: these contracts' producers always set a REQUIRED message or enum, and a list or a map is
        # never null.
        nullable = bool(field.get("proto3Optional"))
        if view.map_entry is not None:
            value = self.value_type(view.map_entry["field"][1], None, False, where)
            record = f"Readonly<Record<string, {value}>>"
            keys = rules.required_keys if rules else ()
            if keys:
                record = "{ " + " ".join(f"readonly {key}: {value};" for key in keys) + f" }} & {record}"
            text = record
        elif field["label"] == "LABEL_REPEATED":
            text = f"readonly {self.value_type(field, view.allowed, open_list, where)}[]"
        else:
            text = self.value_type(field, view.allowed, open_list, where)
        if view.presence == "absent":
            # Written as null when REQUIRED, left out otherwise.
            return f"readonly {field['name']}: null;" if required else None
        if view.presence == "required":
            return f"readonly {field['name']}: {text};"
        if required:
            return f"readonly {field['name']}: {text}{' | null' if nullable else ''};"
        return f"readonly {field['name']}?: {text};"

    def message(self, message: dict[str, Any]) -> list[str]:
        name = self.names[f".{self.package}.{message['name']}"]
        doc = f"/** {self.package}.{message['name']} as wire JSON. */"
        variants = wire_rules.variants(self.file, message, self.enums)
        bodies: list[tuple[list[str], list[str]]] = []  # (discriminator values, members)
        for variant in variants:
            members = [m for m in (self.member(view, message["name"]) for view in variant.fields) if m is not None]
            if variant.value is None:
                if not members:
                    return [doc, f"export interface {name} {{}}"]
                return [doc, f"export interface {name} {{", *(f"  {m}" for m in members), "}"]
            union = wire_rules.discriminator(message)
            rest = [m for m in members if not m.startswith(f"readonly {union}:")]
            for values, others in bodies:
                if others == rest:
                    values.append(variant.value)
                    break
            else:
                bodies.append(([variant.value], rest))
        union = wire_rules.discriminator(message)
        lines = [doc, f"export type {name} ="]
        for values, rest in bodies:
            lines += [
                "  | {",
                f"      readonly {union}: {literal_union(tuple(values))};",
                *(f"      {m}" for m in rest),
                "    }",
            ]
        lines[-1] += ";"
        return lines

    def enum(self, enum: dict[str, Any], name: str, full: str) -> list[str]:
        return [
            f"/** {full}: its wire names (the zero value is never written). */",
            f"export type {name} = {literal_union(wire_rules.wire_names(enum))};",
        ]

    def service(self, service: dict[str, Any], messages: dict[str, dict[str, Any]]) -> list[str]:
        name = service["name"]
        lines = [
            f"/** {self.package}.{name} as the methods of a Workers service binding (wire JSON in and out). */",
            f"export interface {name} {{",
        ]
        for method in service.get("method", []):
            where = f"{self.package}.{name}.{method['name']}"
            output = self.type_name(method["outputType"], where)
            if wire_rules.positional(method):
                request = messages[method["inputType"]]
                params = []
                for field in sorted(request.get("field", []), key=lambda f: f["number"]):
                    view = wire_rules.FieldView(field, None, None, "", None, None, None)
                    member = self.member(view, request["name"])
                    assert member is not None
                    optional = "?" if member.startswith(f"readonly {field['name']}?") else ""
                    params.append(f"{camel(field['name'])}{optional}: {member.split(': ', 1)[1].rstrip(';')}")
                lines.append(f"  {lower_first(method['name'])}({', '.join(params)}): Promise<{output}>;")
            else:
                request = self.type_name(method["inputType"], where)
                lines.append(f"  {lower_first(method['name'])}(input: {request}): Promise<{output}>;")
        lines.append("}")
        return lines

    def write(self) -> str:
        body: list[str] = []
        for enum in self.file.get("enumType", []):
            body += ["", *self.enum(enum, enum["name"], f"{self.package}.{enum['name']}")]
        messages = {f".{self.package}.{m['name']}": m for m in self.file.get("messageType", [])}
        for message in self.file.get("messageType", []):
            for nested in message.get("enumType", []):
                body += [
                    "",
                    *self.enum(
                        nested,
                        f"{message['name']}_{nested['name']}",
                        f"{self.package}.{message['name']}.{nested['name']}",
                    ),
                ]
        for message in self.file.get("messageType", []):
            body += ["", *self.message(message)]
        for service in self.file.get("service", []):
            body += ["", *self.service(service, messages)]
        depth = self.file["name"].count("/")
        registry = []
        for message in self.file.get("messageType", []):
            full = f"{self.package}.{message['name']}"
            registry.append(f"    '{full}': {self.names['.' + full]};")
        return "\n".join(
            [
                HEADER.format(source=self.file["name"]).rstrip("\n"),
                f"/** The wire JSON of {self.package} ({self.file['name']}): types only (tools/gen_wire_ts.py). */",
                *body,
                "",
                "// toWire(<Message>Schema, m) answers these types where this module is imported (ts/wire-json.ts).",
                f"declare module '{'../' * depth}wire-json.ts' {{",
                "  interface WireTypes {",
                *registry,
                "  }",
                "}",
                "",
            ]
        )


def generate(image: dict[str, Any]) -> dict[str, str]:
    """Relative output path -> source, for every file of WIRE_PACKAGES."""
    enums = wire_rules.enum_index(image)
    out: dict[str, str] = {}
    for file in sorted(image["file"], key=lambda f: f["name"]):
        if file.get("package") not in WIRE_PACKAGES:
            continue
        package = file["package"]
        names = {f".{package}.{m['name']}": m["name"] for m in file.get("messageType", [])}
        names |= {f".{package}.{e['name']}": e["name"] for e in file.get("enumType", [])}
        for message in file.get("messageType", []):
            for nested in message.get("enumType", []):
                names[f".{package}.{message['name']}.{nested['name']}"] = f"{message['name']}_{nested['name']}"
        out[file["name"][: -len(".proto")] + "_wire.ts"] = FileWriter(file, enums, names).write()
    return out


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print("usage: gen_wire_ts.py OUT_DIR < image.json", file=sys.stderr)
        return 2
    try:
        files = generate(json.load(sys.stdin))
    except (GenerateError, wire_rules.RuleError) as error:
        print(f"gen_wire_ts: {error}", file=sys.stderr)
        return 1
    root = Path(argv[1])
    for path, source in files.items():
        target = root / path
        target.parent.mkdir(parents=True, exist_ok=True)
        with open(target, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(source)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
