"""Generates stdlib-only Python modules for the wire JSON profile from a buf image (proto/README.md).

Usage (tools/ensure.mjs runs it; never by hand)::

    buf build --exclude-imports --exclude-source-info -o -#format=json \
        | python3 tools/gen_py.py OUT_DIR

For every file of the module, ``todofy/taskintent/v1/task_intent.proto`` say, it writes
``OUT_DIR/todofy/taskintent/v1/task_intent_pb.py`` (plus an empty ``__init__.py`` in every directory):
one ``IntEnum`` per enum, one frozen dataclass per message and a ``FIELDS`` table that the hand-written
runtime ``ziyixi_proto.wire_json`` reads and writes. OUT_DIR is the ``ziyixi_proto`` package directory.
An enum nested in a message is a top-level ``IntEnum`` named ``<Message>_<Enum>``, as protobuf-es names
it (``Send_State``); a map field is a ``dict``; a field whose name is a Python keyword is the attribute
``<name>_`` (PEP 8: mail.received.v1's ``from`` is ``from_``), its wire name unchanged. Services are not
generated (the profile is about messages).

Only the packages a Python user imports are generated (PYTHON_PACKAGES): a package that only TypeScript
apps use (an app's UI API) may use what this profile lacks without stopping generation for every app.

Why not protoc's Python output: todofy-core runs stdlib-only on Pyodide, and the contracts' wire format is
JSON, not protobuf binary. Only the field kinds the contracts use are supported; anything else stops
generation with an error, so a new kind cannot slip through. The output depends only on the image, so
generation is deterministic (the "Proto checks" CI job generates twice and compares).

Runs on Python 3.9 or newer (the system python3 of a developer machine); the generated code needs 3.12.
"""

from __future__ import annotations

import json
import keyword
import sys
from pathlib import Path
from typing import Any

import wire_rules

PACKAGE = "ziyixi_proto"
HEADER = "# Generated by proto/tools/gen_py.py from proto/{source}. DO NOT EDIT; never committed.\n"
# protobuf type -> (Python annotation, default, wire_json kind)
SCALARS = {
    "TYPE_STRING": ("str", '""', "string"),
    "TYPE_BOOL": ("bool", "False", "bool"),
    "TYPE_INT32": ("int", "0", "int32"),
    "TYPE_DOUBLE": ("float", "0.0", "double"),
}
TIMESTAMP = ".google.protobuf.Timestamp"
FIELD_MASK = ".google.protobuf.FieldMask"
# The proto packages generated for Python: True when the package ships in the wheel (todofy-core imports
# todofy.taskintent.v1, todofy.report.v1, ops.v1 and mailhero.webhook.v1, and pywrangler vendors the wheel), False
# when only proto/'s own Python tests use it (python/build_backend.py leaves it out of the wheel: TEST_ONLY_PACKAGES).
# Every other package is TypeScript only. .github/scripts/test_proto.py keeps this, the wheel and the apps' imports in
# step.
PYTHON_PACKAGES = {
    "todofy.taskintent.v1": True,
    "todofy.report.v1": True,
    "ops.v1": True,
    "mailhero.webhook.v1": True,
    "prototest.v1": False,
}
REQUIRED_OPTION = "[google.api.field_behavior]"


class GenerateError(Exception):
    """The image uses something the wire profile does not support."""


def floats(value: float) -> str:
    """A bound as Python source (an integral bound as an integer: 0, not 0.0)."""
    return str(int(value)) if value.is_integer() else repr(value)


def literal(value: str) -> str:
    """A Python string literal of ``value``, ASCII only. JSON's escapes are Python's, except above U+FFFF: JSON writes a
    surrogate pair that a JSON reader joins but Python reads as two characters, so those are written as ``\\U``."""
    return "".join(f"\\U{ord(c):08x}" if ord(c) > 0xFFFF else json.dumps(c)[1:-1] for c in value).join('""')


def strings(values: Any) -> str:
    """A frozenset of strings as Python source, in sorted order (deterministic output)."""
    return "frozenset({" + ", ".join(literal(v) for v in sorted(values)) + "})"


def format_literal(fmt: wire_rules.Format) -> str:
    """A field's reference to its file's format (the module's FORMATS table)."""
    return f"FORMATS[{json.dumps(fmt.name)}]"


def bounds_args(bounds: wire_rules.Bounds) -> list[str]:
    out = []
    if bounds.allowed is not None:
        out.append(f"allowed={strings(bounds.allowed)}")
    if bounds.minimum is not None:
        out.append(f"minimum={floats(bounds.minimum)}")
    if bounds.maximum is not None:
        out.append(f"maximum={floats(bounds.maximum)}")
    if bounds.empty:
        out.append("empty=True")
    return out


def rules_literal(rules: wire_rules.FieldRules | None) -> str:
    """The ``Rules(...)`` of a field (wire_json.py), or "" for a field without rules."""
    if rules is None:
        return ""
    args = []
    if rules.format is not None:
        args.append(f"format={format_literal(rules.format)}")
    args += bounds_args(rules.bounds)
    if rules.open:
        args.append("open=True")
    if rules.max_items:
        args.append(f"max_items={rules.max_items}")
    if rules.unique:
        args.append("unique=True")
    if rules.key_format is not None:
        args.append(f"key_format={format_literal(rules.key_format)}")
    if rules.required_keys:
        args.append(f"required_keys=({''.join(literal(k) + ', ' for k in rules.required_keys)})")
    if rules.keep_order:
        args.append("keep_order=True")
    if rules.cases:
        cases = []
        for case in rules.cases:
            parts = [strings(case.when)]
            if case.presence:
                parts.append(f"presence={json.dumps(case.presence)}")
            if bounds_args(case.bounds):
                parts.append(f"bounds=Bounds({', '.join(bounds_args(case.bounds))})")
            cases.append(f"Case({', '.join(parts)})")
        args.append(f"cases=({''.join(c + ', ' for c in cases)})")
    if rules.otherwise:
        args.append(f"otherwise={json.dumps(rules.otherwise)}")
    if rules.non_null:
        args.append("non_null=True")
    if rules.write_empty:
        args.append("write_empty=True")
    if rules.present_when:
        args.append(f"present_when={json.dumps(rules.present_when)}")
    return f"Rules({', '.join(args)})"


def attribute(name: str) -> str:
    """A field's Python attribute: its name, or ``<name>_`` for a Python keyword (``from`` is ``from_``)."""
    return f"{name}_" if keyword.iskeyword(name) else name


def enum_prefix(name: str) -> str:
    """AIP-126 / buf ENUM_VALUE_PREFIX: ErrorCode -> ERROR_CODE_."""
    out = "".join(f"_{c}" if c.isupper() and i > 0 else c for i, c in enumerate(name))
    return out.upper() + "_"


def module_of(proto_path: str) -> str:
    """todofy/taskintent/v1/task_intent.proto -> todofy.taskintent.v1.task_intent_pb."""
    if not proto_path.endswith(".proto"):
        raise GenerateError(f"{proto_path}: not a .proto file")
    return proto_path[: -len(".proto")].replace("/", ".") + "_pb"


def index_types(image: dict[str, Any]) -> dict[str, tuple[str, str]]:
    """Full type name (".pkg.Name") -> (module, class name) for every top-level type of the image and every
    enum nested in a top-level message (".pkg.Message.Enum" -> "Message_Enum")."""
    types: dict[str, tuple[str, str]] = {}
    for file in image["file"]:
        module = module_of(file["name"])
        for kind in ("enumType", "messageType"):
            for desc in file.get(kind, []):
                types[f".{file['package']}.{desc['name']}"] = (module, desc["name"])
        for message in file.get("messageType", []):
            for nested in message.get("enumType", []):
                types[f".{file['package']}.{message['name']}.{nested['name']}"] = (
                    module,
                    f"{message['name']}_{nested['name']}",
                )
    return types


def map_entries(message: dict[str, Any]) -> dict[str, dict[str, Any]]:
    """The map entry types nested in ``message`` (protoc's synthetic ``<Field>Entry``), by local name."""
    return {
        nested["name"]: nested for nested in message.get("nestedType", []) if nested.get("options", {}).get("mapEntry")
    }


def generate_file(file: dict[str, Any], types: dict[str, tuple[str, str]], enums: dict[str, dict[str, Any]]) -> str:
    """The Python source of one .proto file."""
    module = module_of(file["name"])
    package = file["package"]
    imports: set[str] = set()
    body: list[str] = []
    tables: list[str] = []
    unions: list[str] = []
    matches: list[str] = []
    closed: list[str] = []
    # AnyMatch annotates the ANY_MATCH table of every module.
    runtime = {"AnyMatch", "Field", "Format"}

    def ref(type_name: str, where: str) -> str:
        if type_name not in types:
            raise GenerateError(f"{where}: {type_name} is not in this module (only the profile's types are)")
        owner, name = types[type_name]
        if owner == module:
            return name
        alias = owner.replace(".", "_")
        imports.add(f"import {PACKAGE}.{owner} as {alias}")
        return f"{alias}.{name}"

    def add_enum(enum_type: dict[str, Any], python_name: str, full_name: str) -> None:
        prefix = enum_prefix(enum_type["name"])
        values = enum_type["value"]
        if not values or values[0]["number"] != 0 or not values[0]["name"].endswith("_UNSPECIFIED"):
            raise GenerateError(f"{full_name}: the zero value must be *_UNSPECIFIED")
        body.extend(["", "", f"class {python_name}(enum.IntEnum):"])
        body.extend([f'    """{full_name}; wire names are lower case without {prefix}."""', ""])
        if wire_rules.closed(enum_type):
            closed.append(python_name)
        for value in values:
            if not value["name"].startswith(prefix):
                raise GenerateError(f"{full_name}.{value['name']} lacks the prefix {prefix}")
            body.append(f"    {value['name'][len(prefix) :]} = {value['number']}")

    for enum_type in file.get("enumType", []):
        add_enum(enum_type, enum_type["name"], f"{package}.{enum_type['name']}")
    for message in file.get("messageType", []):
        for nested in message.get("enumType", []):
            add_enum(nested, f"{message['name']}_{nested['name']}", f"{package}.{message['name']}.{nested['name']}")

    def value_kind(field: dict[str, Any], where: str) -> tuple[str, str, str]:
        """(annotation, wire_json kind, ref) of a singular value: a field, a list item or a map value."""
        if field["type"] in SCALARS:
            annotation, _, kind = SCALARS[field["type"]]
            return annotation, kind, "None"
        if field["type"] == "TYPE_ENUM":
            target = ref(field["typeName"], where)
            return target, "enum", target
        if field["type"] == "TYPE_MESSAGE" and field["typeName"] == TIMESTAMP:
            return "str", "timestamp", "None"
        if field["type"] == "TYPE_MESSAGE" and field["typeName"] == FIELD_MASK:
            return "tuple[str, ...]", "fieldmask", "None"
        if field["type"] == "TYPE_MESSAGE":
            target = ref(field["typeName"], where)
            return target, "message", target
        raise GenerateError(f"{where}: {field['type']} is not in the profile")

    def extras(field: dict[str, Any], message: dict[str, Any], entry: dict[str, Any] | None) -> str:
        """The keyword arguments of a Field after the required ones: declared_optional and the value rules."""
        out = ""
        if field.get("proto3Optional", False):
            out += ", declared_optional=True"
        if attribute(field["name"]) != field["name"]:
            out += f", attr={json.dumps(attribute(field['name']))}"
        rules = rules_literal(wire_rules.field_rules(file, message, field, enums, entry))
        if rules:
            out += f", rules={rules}"
            runtime.update(name for name in ("Rules", "Case", "Bounds") if f"{name}(" in rules)
        return out

    for message in file.get("messageType", []):
        name = message["name"]
        union = wire_rules.discriminator(message)
        if union is not None:
            unions.append(f"    {name}: {json.dumps(union)},")
        groups = wire_rules.any_matches(file, message)
        if groups:
            literals = "".join(
                f"AnyMatch(({''.join(json.dumps(f) + ', ' for f in group.fields)}), {format_literal(group.format)}), "
                for group in groups
            )
            matches.append(f"    {name}: ({literals}),")
        attributes = [attribute(f["name"]) for f in message.get("field", [])]
        if len(set(attributes)) != len(attributes):
            raise GenerateError(f"{package}.{name}: two fields have the same Python attribute (a keyword's name_)")
        entries = map_entries(message)
        if len(entries) != len(message.get("nestedType", [])):
            raise GenerateError(f"{package}.{name}: nested messages are not in the profile (only map entries)")
        # proto3 `optional` declares a synthetic oneof per field; a real oneof is not in the profile.
        if any("oneofIndex" in f and not f.get("proto3Optional") for f in message.get("field", [])):
            raise GenerateError(f"{package}.{name}: oneofs are not in the profile")
        body += ["", "", "@dataclasses.dataclass(frozen=True, slots=True, kw_only=True)", f"class {name}:"]
        body += [f'    """{package}.{name}."""', ""]
        fields: list[str] = []
        for field in sorted(message.get("field", []), key=lambda f: f["number"]):
            where = f"{package}.{name}.{field['name']}"
            repeated = field["label"] == "LABEL_REPEATED"
            optional = bool(field.get("proto3Optional", False))
            required = "REQUIRED" in field.get("options", {}).get(REQUIRED_OPTION, [])
            value = ""
            entry_name = field.get("typeName", "").rsplit(".", 1)[-1]
            attr = attribute(field["name"])
            if (
                field["type"] == "TYPE_MESSAGE"
                and field["typeName"] == f".{package}.{name}.{entry_name}"
                and entry_name in entries
            ):
                key_field, value_field = sorted(entries[entry_name]["field"], key=lambda f: f["number"])
                if key_field["type"] != "TYPE_STRING":
                    raise GenerateError(f"{where}: only string map keys are in the profile")
                value_annotation, value, target = value_kind(value_field, where)
                if value in ("timestamp", "fieldmask"):
                    raise GenerateError(f"{where}: Timestamp and FieldMask map values are not in the profile")
                body.append(f"    {attr}: dict[str, {value_annotation}] = dataclasses.field(default_factory=dict)")
                fields.append(
                    f'Field({json.dumps(field["name"])}, {field["number"]}, "map", {target}, '
                    f"repeated=False, optional=False, required={required}, value={json.dumps(value)}"
                    f"{extras(field, message, entries[entry_name])})"
                )
                continue
            annotation, kind, target = value_kind(field, where)
            if kind in ("timestamp", "fieldmask", "message"):
                default, optional = "None", True  # a message field has explicit presence
            elif kind == "enum":
                default = f"{annotation}.UNSPECIFIED"
            else:
                default = SCALARS[field["type"]][1]
            if repeated:
                annotation, default = f"tuple[{annotation}, ...]", "()"
            elif optional:
                annotation, default = f"{annotation} | None", "None"
            body.append(f"    {attr}: {annotation} = {default}")
            fields.append(
                f"Field({json.dumps(field['name'])}, {field['number']}, {json.dumps(kind)}, {target}, "
                f"repeated={repeated}, optional={optional}, required={required}{extras(field, message, None)})"
            )
        if not fields:
            body.append("    pass")
        tables.append(f"    {name}: (\n" + "".join(f"        {f},\n" for f in fields) + "    ),")

    lines = [
        HEADER.format(source=file["name"]).rstrip("\n"),
        f'"""{package} ({file["name"]}) in the wire JSON profile; read and write with {PACKAGE}.wire_json."""',
        "",
        "# Annotations may name a message defined further down (or in a module imported below).",
        "from __future__ import annotations",
        "",
        "import dataclasses",
        "import enum",
        "",
        *sorted(imports),
        f"from {PACKAGE}.wire_json import {', '.join(sorted(runtime))}",
        *body,
        "",
        "",
        "# The file's named string formats (common.wire.v1.formats): wire_json.format_matches(FORMATS[name], value).",
        "FORMATS: dict[str, Format] = {",
        *(
            f"    {json.dumps(f.name)}: Format({json.dumps(f.name)}, {literal(f.pattern)}, {f.max_length}),"
            for f in wire_rules.formats(file).values()
        ),
        "}",
        "",
        "# Field tables of the wire JSON profile, in field-number order, with their value rules.",
        "FIELDS: dict[type, tuple[Field, ...]] = {",
        *tables,
        "}",
        "",
        "# Union messages: the name of each one's discriminator field (common.wire.v1.Message).",
        "UNIONS: dict[type, str] = {",
        *unions,
        "}",
        "",
        "# Messages with groups of fields of which one must match a format (common.wire.v1.Message.any_match).",
        "ANY_MATCH: dict[type, tuple[AnyMatch, ...]] = {",
        *matches,
        "}",
        "",
        "# Closed enums ((common.wire.v1.closed)): every read refuses a wire name it does not know.",
        f"CLOSED: frozenset[type] = frozenset({{{', '.join(closed)}}})"
        if closed
        else "CLOSED: frozenset[type] = frozenset()",
        "",
    ]
    return "\n".join(lines)


def python_files(image: dict[str, Any]) -> dict[str, Any]:
    """The image restricted to the files of PYTHON_PACKAGES (a reference to another package fails later)."""
    return {**image, "file": [file for file in image["file"] if file.get("package") in PYTHON_PACKAGES]}


def generate(image: dict[str, Any]) -> dict[str, str]:
    """Relative output path -> source, for every file of PYTHON_PACKAGES and every package directory. The value
    rules of every file are checked first, a TypeScript-only package's too (wire_rules.check_image)."""
    try:
        wire_rules.check_image(image)
    except wire_rules.RuleError as error:
        raise GenerateError(str(error)) from None
    enums = wire_rules.enum_index(image)
    image = python_files(image)
    types = index_types(image)
    out: dict[str, str] = {}
    for file in sorted(image["file"], key=lambda f: f["name"]):
        if file.get("syntax") != "proto3":
            raise GenerateError(f"{file['name']}: only proto3 files are in the profile")
        module = module_of(file["name"])
        parts = module.split(".")
        for depth in range(1, len(parts)):
            out["/".join(parts[:depth]) + "/__init__.py"] = ""
        out["/".join(parts) + ".py"] = generate_file(file, types, enums)
    return out


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print("usage: gen_py.py OUT_DIR < image.json", file=sys.stderr)
        return 2
    try:
        files = generate(json.load(sys.stdin))
    except (GenerateError, wire_rules.RuleError) as error:
        print(f"gen_py: {error}", file=sys.stderr)
        return 1
    root = Path(argv[1])
    for path, source in files.items():
        target = root / path
        target.parent.mkdir(parents=True, exist_ok=True)
        with open(target, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(source)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
