import { validateLiteralRedirectSource } from "../../src/lib/content/redirect-path";

/**
 * Response headers of the static export, written to out/_headers (Workers Static Assets). The
 * security headers are exactly the ones next.config.ts headers() sent on Vercel; HSTS keeps the value
 * Vercel sent (the zone's own HSTS is off), without includeSubDomains or preload because other
 * subdomains of ziyixi.science are separate apps.
 */
export const SECURITY_HEADERS: readonly (readonly [string, string])[] = [
  ["Referrer-Policy", "strict-origin-when-cross-origin"],
  ["X-Content-Type-Options", "nosniff"],
  ["X-Frame-Options", "DENY"],
  ["Permissions-Policy", "camera=(), microphone=(), geolocation=()"],
  ["Strict-Transport-Security", "max-age=63072000"],
];

/**
 * Vercel answered every static response with `Access-Control-Allow-Origin: *`; browser-based feed
 * readers and cross-origin reads of /feed.xml or /build-info.json depend on it. Everything here is
 * public and cookie-free. (Vercel's OPTIONS 204 has no equivalent without a Worker script; simple
 * cross-origin GETs need no preflight.)
 */
export const CORS_HEADERS: readonly (readonly [string, string])[] = [
  ["Access-Control-Allow-Origin", "*"],
];

export const NO_STORE = "no-store, max-age=0";
export const IMMUTABLE = "public, max-age=31536000, immutable";

/** Path rules after the site-wide one; each header name appears in one rule only. */
export const PATH_HEADERS: readonly {
  path: string;
  headers: readonly (readonly [string, string])[];
}[] = [
  // The release verifier and the Notion status check read these; they must never be cached.
  { path: "/build-info.json", headers: [["Cache-Control", NO_STORE]] },
  { path: "/publication-state.json", headers: [["Cache-Control", NO_STORE]] },
  // The asset server would guess application/xml from the extension.
  {
    path: "/feed.xml",
    headers: [
      ["Content-Type", "application/rss+xml; charset=utf-8"],
      ["Cache-Control", "public, max-age=0, must-revalidate"],
    ],
  },
  // Content-addressed files: Next's hashed chunks, sha256-named media, hashed image variants.
  { path: "/_next/static/*", headers: [["Cache-Control", IMMUTABLE]] },
  { path: "/media/*", headers: [["Cache-Control", IMMUTABLE]] },
  { path: "/_img/*", headers: [["Cache-Control", IMMUTABLE]] },
];

export function renderHeadersFile(): string {
  const blocks = [
    [
      "/*",
      ...[...SECURITY_HEADERS, ...CORS_HEADERS].map(([name, value]) => `  ${name}: ${value}`),
    ].join("\n"),
    ...PATH_HEADERS.map((rule) =>
      [rule.path, ...rule.headers.map(([name, value]) => `  ${name}: ${value}`)].join("\n"),
    ),
  ];
  return `# Generated by scripts/export/finalize.ts from scripts/export/site-files.ts; do not edit.\n${blocks.join("\n\n")}\n`;
}

export interface ExportRedirect {
  from: string;
  to: string;
}

/** Workers Static Assets limits: 2,000 static redirects, 1,000 characters per line. */
export const MAX_STATIC_REDIRECTS = 2000;
const MAX_REDIRECT_LINE = 1000;

/** A path as browsers send it: non-ASCII characters percent-encoded (uppercase hex). */
function requestPath(value: string): string {
  return encodeURI(decodeURI(value));
}

/**
 * out/_redirects: literal 308 rules, evaluated before html_handling.
 *
 * - The snapshot's slug-change and configured redirects, each also in its trailing-slash form
 *   (/blog/old/ -> new), which Vercel reached through its own trailing-slash 308.
 * - The trailing-slash form of every canonical page and feed path (/blog/ -> /blog), so these stay
 *   permanent 308s as on Vercel instead of html_handling's 307 (which also 404s /feed.xml/).
 *
 * The content pipeline already validated the snapshot redirects; this re-checks the invariants
 * _redirects depends on (a literal source without placeholders or splats, an internal target, no
 * whitespace) and the Workers limits.
 */
export function renderRedirectsFile(
  redirects: readonly ExportRedirect[],
  canonicalPaths: readonly string[] = [],
): string {
  const seen = new Set<string>();
  const lines: string[] = [];
  const add = (source: string, target: string): void => {
    if (seen.has(source)) throw new Error(`Duplicate redirect source: ${source}`);
    seen.add(source);
    const line = `${source} ${target} 308`;
    if (line.length > MAX_REDIRECT_LINE) throw new Error(`Redirect rule is too long: ${source}`);
    lines.push(line);
  };
  for (const redirect of redirects) {
    const from = validateLiteralRedirectSource(redirect.from);
    if (!redirect.to.startsWith("/") || redirect.to.startsWith("//") || /\s/.test(redirect.to)) {
      throw new Error(`Redirect target must be an internal path: ${redirect.to}`);
    }
    // Browsers send non-ASCII paths percent-encoded; the rule must match that form.
    const target = requestPath(redirect.to);
    add(encodeURI(from), target);
    add(`${encodeURI(from)}/`, target);
  }
  for (const canonical of canonicalPaths) {
    if (canonical === "/") continue;
    if (!canonical.startsWith("/") || canonical.endsWith("/") || /\s/.test(canonical)) {
      throw new Error(`Canonical path must be a path without a trailing slash: ${canonical}`);
    }
    const target = requestPath(canonical);
    add(`${target}/`, target);
  }
  if (lines.length > MAX_STATIC_REDIRECTS) {
    throw new Error(`Too many redirects for _redirects: ${lines.length}`);
  }
  return `# Generated by scripts/export/finalize.ts from the content snapshot; do not edit.\n${lines.map((line) => `${line}\n`).join("")}`;
}

/** Workers Static Assets (Free): 20,000 files per version, 25 MiB per file. */
export const MAX_ASSET_FILES = 20_000;
export const MAX_ASSET_BYTES = 25 * 1024 * 1024;

export function assertAssetLimits(files: readonly { path: string; bytes: number }[]): void {
  if (files.length > MAX_ASSET_FILES) {
    throw new Error(`The export has ${files.length} files; the limit is ${MAX_ASSET_FILES}.`);
  }
  const oversized = files.filter((file) => file.bytes >= MAX_ASSET_BYTES);
  if (oversized.length > 0) {
    throw new Error(
      `Files at or over the 25 MiB static-asset limit: ${oversized.map((file) => file.path).join(", ")}`,
    );
  }
}
