// Generated by `npm run gen:api` from api/owner-api-v1.openapi.yaml. Do not edit.

export interface paths {
    "/api/v1/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Issue a CSRF token and set the matching todofy_csrf cookie. */
        get: operations["getCsrfToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Counters, flags and budgets for the shell and status banner.
         * @description Only active rows are counted, so the cost does not grow with the ledger. The UI refreshes it every five minutes.
         */
        get: operations["getOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List ledger events, newest first (recent) or oldest first (attention). */
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One event with its content preview, allowed actions and timeline. */
        get: operations["getEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply an owner reconcile action.
         * @description The action must be in the event's `allowed_actions` and `version` must equal the
         *     stored version. A replay with the same `action_request_id` and the same request
         *     returns the stored outcome; the same id with a different request is 409
         *     `action_request_conflict`. The response shows the committed transition; any
         *     follow-up work (lookup, summary, task creation) runs later in the Worker.
         */
        post: operations["reconcileEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reminders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daily reminder rows, newest UTC day first. */
        get: operations["listReminders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The stored reports exactly as the newsletter endpoints return them. */
        get: operations["getLatestReports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/recompute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recompute one report now (calls Gemini unless the window is empty).
         * @description Shares the hourly report-computation cap with the newsletter endpoints; over it the answer is 429 `rate_limited`.
         */
        post: operations["recomputeReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Daily mail, latency, Gemini and Todoist counters for the budget page's trends.
         * @description The finished UTC days before today, oldest first. The coordinator writes each day
         *     once, a few minutes after UTC midnight, from the day's ledger transitions and its
         *     own step counters. A day it did not count completely (before metrics began, or
         *     after its storage was reset) is `recorded: false` with zero counters.
         */
        get: operations["getDailyMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gtd/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The GTD ledger's daily Todoist aggregates and the latest weekly review.
         * @description Counts from the daily read-only Todoist snapshot (13:00 UTC), per scope: every project
         *     (`all`) and the inbox (`TODOIST_DEFAULT_PROJECT_ID`). Numbers only, never task text. Days
         *     up to today, oldest first; a day without a snapshot is `recorded: false`. Kept 120 days.
         */
        get: operations["getGtdDaily"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/legacy_text/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full mail text imported from the retired Go cache. */
        get: operations["getLegacyText"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Integration facts for the setup page; never secret values. */
        get: operations["getSetup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hooks/mail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept one Mail Hero mail.received.v1 event.
         * @description 204 is sent only after the event is committed to D1. Replaying the same bytes is
         *     204 again without new work, even for ledger rows imported from the Go service;
         *     the same `event_id` with different bytes is 409.
         */
        post: operations["receiveMail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The daily summary for the newsletter. */
        get: operations["getDailySummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recommendation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The ranked tasks for the newsletter. */
        get: operations["getRecommendation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The deployed build, for the post-deploy check. */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @example {
         *       "error": {
         *         "code": "version_conflict",
         *         "message": "事件已被更新，请刷新后重试",
         *         "request_id": "8c3f0e6d2a1b4c5d"
         *       }
         *     }
         */
        Error: {
            error: {
                code: components["schemas"]["ApiErrorCode"];
                /** @description Short Chinese text for the UI; never mail content or upstream response bodies. */
                message: string;
                /** @description Quote it when reporting a problem; it appears in the Worker logs. */
                request_id: string;
            };
        };
        /** @enum {string} */
        ApiErrorCode: "invalid_request" | "invalid_payload" | "unauthorized" | "csrf_failed" | "not_found" | "event_conflict" | "version_conflict" | "action_not_allowed" | "action_request_conflict" | "payload_too_large" | "unsupported_media_type" | "rate_limited" | "internal_error" | "maintenance" | "not_configured" | "access_not_configured" | "unavailable";
        /** Format: date-time */
        Timestamp: string;
        /**
         * Format: uuid
         * @description Mail Hero event ID.
         */
        EventId: string;
        /** @enum {string} */
        EventState: "pending" | "summarizing" | "summarized" | "todo_sending" | "todo_unknown" | "todo_created" | "complete" | "ignored" | "failed_summary";
        EventErrorCode: components["schemas"]["CurrentEventErrorCode"] | components["schemas"]["LegacyEventErrorCode"];
        /** @enum {string} */
        CurrentEventErrorCode: "mail_needs_review" | "summary_failed" | "llm_quota" | "llm_budget_exhausted" | "llm_request_rejected" | "processing_interrupted_limit" | "todoist_rejected" | "todoist_auth_blocked" | "todoist_rate_limited" | "todoist_unavailable" | "todo_result_unknown" | "interrupted_todo_call" | "lookup_not_found" | "lookup_failed" | "lookup_ambiguous" | "dismissed_by_owner" | "canary_side_effect_blocked";
        /** @enum {string} */
        LegacyEventErrorCode: "invalid_saved_event" | "llm_client_unavailable" | "summary_render_failed" | "todo_client_unavailable" | "database_client_unavailable" | "cache_write_failed" | "checkpoint_failed";
        /** @enum {string} */
        ReminderState: "sending" | "created" | "unknown" | "failed";
        ReminderErrorCode: components["schemas"]["CurrentReminderErrorCode"] | components["schemas"]["LegacyReminderErrorCode"];
        /** @enum {string} */
        CurrentReminderErrorCode: "reminder_create_failed" | "reminder_result_unknown" | "interrupted_reminder_call";
        /** @enum {string} */
        LegacyReminderErrorCode: "empty_task_id" | "todo_client_unavailable";
        /**
         * @description - task_created: the owner found the Todoist task (`task_id` required); the event completes with it.
         *     - task_not_created: the owner found no task. A footer lookup runs first, then the frozen request is sent again, which can duplicate a task.
         *     - retry_summary: summarize again; not offered for mail_needs_review.
         *     - dismiss: give up without checking Todoist; the event becomes ignored. Offered for failed_summary, todo_unknown, and summarized rows whose last Todoist request was refused (todoist_rejected).
         * @enum {string}
         */
        ReconcileAction: "task_created" | "task_not_created" | "retry_summary" | "dismiss";
        /** @enum {string} */
        TransitionActor: "worker" | "owner";
        EventSummary: {
            event_id: components["schemas"]["EventId"];
            state: components["schemas"]["EventState"];
            error_code: components["schemas"]["EventErrorCode"] | null;
            attempt_count: number;
            /** @description Todoist task ID once known; link it as https://app.todoist.com/app/task/<id>. */
            task_id: string | null;
            received_at: components["schemas"]["Timestamp"];
            updated_at: components["schemas"]["Timestamp"];
            /** @description When the Worker acts on the event next; null when nothing is scheduled. */
            next_attempt_at: components["schemas"]["Timestamp"] | null;
            /** @description failed_summary or todo_unknown, or not terminal and received at least 6 hours ago. */
            attention: boolean;
            /** @description Imported from the Go service's ledger. */
            imported: boolean;
        };
        /**
         * @example {
         *       "event_id": "f8c1e9a0-1a98-4fb8-8ca1-4c0a3e710001",
         *       "state": "todo_unknown",
         *       "error_code": "lookup_not_found",
         *       "attempt_count": 0,
         *       "task_id": null,
         *       "received_at": "2026-09-28T08:00:00Z",
         *       "updated_at": "2026-09-28T08:02:10Z",
         *       "next_attempt_at": null,
         *       "attention": true,
         *       "imported": false,
         *       "version": 5,
         *       "crashes": 0,
         *       "subject": "Quarterly tax reminder",
         *       "from": "billing@example.com",
         *       "summary": "季度预缴税截止日期为 10 月 15 日。",
         *       "summary_model": "gemini-3.8-flash",
         *       "todo_body": "**FROM: billing@example.com**\n...\n\nMail Hero event: f8c1e9a0-1a98-4fb8-8ca1-4c0a3e710001",
         *       "todoist_request_id": "todofy-0123456789abcdef0123456789ab",
         *       "allowed_actions": [
         *         "task_created",
         *         "task_not_created",
         *         "dismiss"
         *       ],
         *       "transitions": [
         *         {
         *           "at": "2026-09-28T08:00:00Z",
         *           "from_state": null,
         *           "to_state": "pending",
         *           "error_code": null,
         *           "actor": "worker"
         *         },
         *         {
         *           "at": "2026-09-28T08:00:20Z",
         *           "from_state": "summarized",
         *           "to_state": "todo_unknown",
         *           "error_code": "todo_result_unknown",
         *           "actor": "worker"
         *         }
         *       ],
         *       "has_legacy_text": false
         *     }
         */
        EventDetail: components["schemas"]["EventSummary"] & {
            /** @description Send it back with a reconcile action. */
            version: number;
            /** @description Summary runs interrupted mid-call; three stop automatic retries. */
            crashes: number;
            /** @description From the stored event, or from the report cache once complete; null for imported rows without either. */
            subject: string | null;
            /** @description First From address while the event body is still stored. */
            from: string | null;
            summary: string | null;
            summary_model: string | null;
            /** @description The frozen Todoist description, footer included; plain text. */
            todo_body: string | null;
            todoist_request_id: string | null;
            allowed_actions: components["schemas"]["ReconcileAction"][];
            /** @description Oldest first; the first 100 transitions. */
            transitions: components["schemas"]["Transition"][];
            /** @description GET /api/v1/legacy_text/{event_id} has the imported full text. */
            has_legacy_text: boolean;
            /**
             * @description Present (true) only for a synthetic canary event (contracts/ops-v1): processed through Gemini but never sent to Todoist, listed, counted or reminded of.
             * @constant
             */
            canary?: true;
        };
        Transition: {
            at: components["schemas"]["Timestamp"];
            /** @description Null for the event's arrival. */
            from_state: components["schemas"]["EventState"] | null;
            to_state: components["schemas"]["EventState"];
            error_code: components["schemas"]["EventErrorCode"] | null;
            actor: components["schemas"]["TransitionActor"];
        };
        EventPage: {
            items: components["schemas"]["EventSummary"][];
            next_cursor: string | null;
        };
        /**
         * @example {
         *       "action": "task_created",
         *       "version": 5,
         *       "action_request_id": "3b0d7a52-8f0e-4a8e-9a55-2f0f6c1d9e11",
         *       "task_id": "6X7rM8997g3RQmvh"
         *     }
         * @example {
         *       "action": "dismiss",
         *       "version": 5,
         *       "action_request_id": "0e8f7a55-1c2d-4e5f-8a9b-0c1d2e3f4a5b"
         *     }
         */
        ReconcileRequest: {
            action: components["schemas"]["ReconcileAction"];
            version: number;
            /**
             * Format: uuid
             * @description A fresh random UUID per user action; reuse it only to retry the same request.
             */
            action_request_id: string;
            task_id?: string;
        };
        Reminder: {
            /**
             * Format: date
             * @description UTC day.
             */
            day: string;
            state: components["schemas"]["ReminderState"];
            task_id: string | null;
            attention_count: number;
            attempts: number;
            error_code: components["schemas"]["ReminderErrorCode"] | null;
            next_attempt_at: components["schemas"]["Timestamp"] | null;
            created_at: components["schemas"]["Timestamp"];
            updated_at: components["schemas"]["Timestamp"];
            imported: boolean;
        };
        ReminderPage: {
            items: components["schemas"]["Reminder"][];
            next_cursor: string | null;
        };
        /**
         * @example {
         *       "build": "0123456789abcdef0123456789abcdef01234567",
         *       "now": "2026-09-28T12:00:00Z",
         *       "flags": {
         *         "maintenance_mode": false,
         *         "processing_paused": false,
         *         "force_pause_todoist": false,
         *         "reminder_enabled": true
         *       },
         *       "counts": {
         *         "pending": 1,
         *         "summarizing": 0,
         *         "summarized": 0,
         *         "todo_sending": 0,
         *         "todo_unknown": 1,
         *         "todo_created": 0,
         *         "failed_summary": 0
         *       },
         *       "attention_count": 1,
         *       "received_24h": 42,
         *       "latest_reminder": null,
         *       "next_alarm_at": "2026-09-28T12:00:01Z",
         *       "oldest_due_at": "2026-09-28T11:59:00Z",
         *       "gemini": {
         *         "day": "2026-09-28",
         *         "token_budget": 3000000,
         *         "reserved_tokens": 4096,
         *         "used_tokens": 181233,
         *         "calls": 41,
         *         "models": [
         *           "gemini-3.8-flash",
         *           "gemini-3.7-flash",
         *           "gemini-3.5-flash-lite"
         *         ]
         *       },
         *       "todoist": {
         *         "blocked_until": null,
         *         "window_seconds": 900,
         *         "window_calls": 3,
         *         "window_limit": 1000
         *       },
         *       "backup": {
         *         "status": "ok",
         *         "last_backup_at": "2026-09-27T10:00:41Z",
         *         "last_backup_key": "backups/2026-09-27T100002Z/",
         *         "last_backup_bytes": 1843200,
         *         "last_backup_rows": 52311,
         *         "last_failure_at": null,
         *         "last_error_code": null,
         *         "next_backup_at": "2026-10-04T10:00:00Z"
         *       }
         *     }
         */
        Overview: {
            build: string;
            now: components["schemas"]["Timestamp"];
            flags: {
                maintenance_mode: boolean;
                processing_paused: boolean;
                force_pause_todoist: boolean;
                reminder_enabled: boolean;
            };
            /** @description Events per active (non-terminal) state. */
            counts: {
                pending: number;
                summarizing: number;
                summarized: number;
                todo_sending: number;
                todo_unknown: number;
                todo_created: number;
                failed_summary: number;
            };
            attention_count: number;
            received_24h: number;
            latest_reminder: components["schemas"]["Reminder"] | null;
            next_alarm_at: components["schemas"]["Timestamp"] | null;
            /** @description next_attempt_at of the longest-waiting due event; null when nothing is due. */
            oldest_due_at: components["schemas"]["Timestamp"] | null;
            gemini: {
                /** Format: date */
                day: string;
                token_budget: number;
                reserved_tokens: number;
                used_tokens: number;
                calls: number;
                /** @description Fallback order. */
                models: string[];
            };
            todoist: {
                /** @description Task creation is paused until then after a 401/403. */
                blocked_until: components["schemas"]["Timestamp"] | null;
                window_seconds: number;
                window_calls: number;
                window_limit: number;
            };
            backup?: components["schemas"]["BackupStatus"];
        };
        /**
         * @description The weekly D1 backup to the private R2 bucket (Sunday 10:00 UTC), every table in
         *     each one. While a backup runs (a few minutes, never over 30 minutes) the ledger
         *     waits and owner writes get 503 `unavailable`. Not required in Overview so that clients written before it keep
         *     validating; the Worker always sends it.
         */
        BackupStatus: {
            /**
             * @description `disabled`: the Worker has no BACKUPS bucket binding. `never`: no backup finished or failed yet. Otherwise the running job or the last outcome.
             * @enum {string}
             */
            status: "disabled" | "never" | "running" | "ok" | "failed";
            /** @description When the newest complete backup finished. */
            last_backup_at: components["schemas"]["Timestamp"] | null;
            /** @description Its R2 prefix, named after the second its job started, e.g. `backups/2026-09-27T100002Z/` (tools/backup_restore.py reads it). */
            last_backup_key: string | null;
            /** @description Compressed size of its parts and manifest. */
            last_backup_bytes: number;
            /** @description Rows in it. */
            last_backup_rows: number;
            last_failure_at: components["schemas"]["Timestamp"] | null;
            /** @description Why the last failed job stopped. */
            last_error_code: ("storage_error" | "lease_expired") | null;
            /** @description Null while disabled or running. */
            next_backup_at: components["schemas"]["Timestamp"] | null;
        };
        DailyMetrics: {
            days: components["schemas"]["DailyMetricsDay"][];
        };
        /**
         * @example {
         *       "day": "2026-09-27",
         *       "recorded": true,
         *       "mails_received": 64,
         *       "mails_completed": 61,
         *       "mails_failed": 1,
         *       "latency_p50_seconds": 18,
         *       "latency_p90_seconds": 95,
         *       "gemini_calls": 66,
         *       "gemini_tokens": {
         *         "gemini-3.8-flash": 402113,
         *         "gemini-3.7-flash": 8120
         *       },
         *       "todoist_creates": 62,
         *       "todoist_lookups": 1
         *     }
         */
        DailyMetricsDay: {
            /**
             * Format: date
             * @description UTC day.
             */
            day: string;
            /** @description False when the day was not counted; its counters are then 0. */
            recorded: boolean;
            /** @description Webhook events stored. */
            mails_received: number;
            /** @description Events that reached complete. */
            mails_completed: number;
            /** @description Moves to failed_summary (an event retried by the owner can fail again). */
            mails_failed: number;
            /** @description Median seconds from arrival to complete over the day's completions; null without any. */
            latency_p50_seconds: number | null;
            /** @description 90th percentile of the same; null without any completion. */
            latency_p90_seconds: number | null;
            /** @description Gemini requests (summaries and reports; each model tried counts). */
            gemini_calls: number;
            /** @description Tokens by the model that answered (or was tried last). */
            gemini_tokens: {
                [key: string]: number;
            };
            /** @description Task-creation requests (mail tasks */
            todoist_creates: number;
            /** @description Footer lookups (each may read several pages). */
            todoist_lookups: number;
        };
        GtdDaily: {
            days: components["schemas"]["GtdDay"][];
            /** @description The newest weekly review task (at most 12 weeks back), or null. */
            latest_review: components["schemas"]["GtdReview"] | null;
        };
        GtdDay: {
            /**
             * Format: date
             * @description UTC day.
             */
            day: string;
            /** @description Whether the day has a snapshot aggregate. */
            recorded: boolean;
            /** @description Every project; null when the day is not recorded. */
            all: components["schemas"]["GtdScope"] | null;
            /** @description The inbox project; null when not recorded or no inbox project is configured. */
            inbox: components["schemas"]["GtdScope"] | null;
        };
        GtdScope: {
            /** @description Active tasks (sub-tasks included). */
            open: number;
            /** @description Open tasks added 0–7 days ago. */
            age_0_7: number;
            age_8_14: number;
            age_15_30: number;
            /** @description Tasks with an unknown creation time are in no bucket. */
            age_31_plus: number;
            oldest_days: number;
            /** @description A fixed-time due before the snapshot, or a date before its UTC date. */
            overdue: number;
            /** @description Without a due date (a deadline alone does not date a task). */
            undated: number;
            /** @description Added in the last 7 days (open or completed); null without the completed list. */
            created_7d: number | null;
            /** @description Completed in the last 7 days per Todoist's completed list; null when that call failed. */
            completed_7d: number | null;
            /** @enum {string} */
            completed_source: "api" | "none";
            /** @description Tasks in the previous day's snapshot missing from this one (completions and deletions); only for `all`. */
            closed_1d: number | null;
            /** @description Mail tasks that arrived 1 to 14 days before the snapshot (the morning brief's carryover pool, before its cap of 30) still open; only for `all`. */
            mail_open: number | null;
            /** @description False when the snapshot hit its page cap (over 2 */
            complete: boolean;
        };
        GtdReview: {
            /** @description ISO week. */
            week: string;
            /** @enum {string} */
            state: "sending" | "created" | "unknown" | "failed";
            created_at: components["schemas"]["Timestamp"];
            /** @description When the daily snapshot first saw the task completed. */
            completed_at: components["schemas"]["Timestamp"] | null;
        };
        ReportsLatest: {
            summary: components["schemas"]["summary-v1.schema"] | null;
            /** @description The latest stored recommendation for each top_n, ordered by top_n. */
            recommendations: components["schemas"]["recommendation-v1.schema"][];
        };
        RecomputeRequest: {
            /** @enum {string} */
            kind: "summary" | "recommendation";
            /** @description Recommendation only; defaults to REPORT_DEFAULT_TOP. */
            top?: number;
            /** Format: uuid */
            action_request_id: string;
        };
        LegacyText: {
            event_id: string;
            created_at: components["schemas"]["Timestamp"];
            /** @description Null keeps the text forever. */
            expires_at: components["schemas"]["Timestamp"] | null;
            text: string;
        };
        Setup: {
            build: string;
            public_host: string;
            hooks_hosts: string[];
            /** @constant */
            webhook_path: "/hooks/mail";
            mail_source_id: string;
            /** Format: email */
            access_owner: string;
            /** @description Whether each secret or setting is present; values are never returned. */
            configured: {
                mail_webhook_token: boolean;
                report_basic_auth: boolean;
                gemini_api_key: boolean;
                todoist_api_key: boolean;
                todoist_project: boolean;
            };
        };
        Csrf: {
            token: string;
        };
        Health: {
            /** @description BUILD_SHA, the deployed commit. */
            build: string;
            /**
             * @description Kept from the Go service; the newsletter preflight requires it.
             * @enum {string}
             */
            service: "todofy";
            /**
             * @description Kept from the Go service; the newsletter preflight requires it.
             * @enum {string}
             */
            status: "healthy";
            /** Format: date-time */
            timestamp: string;
        };
        /**
         * Todofy GET /api/summary response
         * @description Todofy GET /api/summary response: the daily summary the newsletter reads. summary, task_count and time_window_hours are the Go service's fields (handle_summary.go @ 6c46ed4) and keep their meaning; the rest were added by the Worker. Fields may be added, never removed or retyped, so consumers must ignore unknown fields. The limits are the newsletter's acceptance rules (newsletter src/newsletter/todofy.py _decode), so any response that validates is one the newsletter accepts.
         */
        "summary-v1.schema": {
            /** @description Plain text from the daily-summary prompt, or the legacy English sentence when the window is empty. Not blank; no control characters other than tab, line feed and carriage return. */
            summary: string;
            /** @description Summaries in the window: at least one when ok, none when the window was empty. */
            task_count: number;
            /**
             * @description The window's length: always 24.
             * @constant
             */
            time_window_hours: 24;
            /**
             * @description The Worker sends only ok and empty_window.
             * @constant
             */
            status: "ok";
            /** @description Gemini model name; empty when no model was called. */
            model: string;
            /**
             * Format: date-time
             * @description When the report was computed.
             */
            computed_at: string;
            /**
             * Format: date-time
             * @description The window's start (exclusive): 24 hours before its end.
             */
            window_start: string;
            /**
             * Format: date-time
             * @description The window's end (inclusive): computed_at.
             */
            window_end: string;
        } | {
            /**
             * @description Plain text from the daily-summary prompt, or the legacy English sentence when the window is empty. Not blank; no control characters other than tab, line feed and carriage return.
             * @constant
             */
            summary: "As there is no new task in the last 24 hours, there will have no summary. Please check your service as it's highly not possible that there is no new task in the last 24 hours.\n";
            /**
             * @description Summaries in the window: at least one when ok, none when the window was empty.
             * @constant
             */
            task_count: 0;
            /**
             * @description The window's length: always 24.
             * @constant
             */
            time_window_hours: 24;
            /**
             * @description The Worker sends only ok and empty_window.
             * @constant
             */
            status: "empty_window";
            /** @description Gemini model name; empty when no model was called. */
            model: string;
            /**
             * Format: date-time
             * @description When the report was computed.
             */
            computed_at: string;
            /**
             * Format: date-time
             * @description The window's start (exclusive): 24 hours before its end.
             */
            window_start: string;
            /**
             * Format: date-time
             * @description The window's end (inclusive): computed_at.
             */
            window_end: string;
        } | {
            /** @description Plain text from the daily-summary prompt, or the legacy English sentence when the window is empty. Not blank; no control characters other than tab, line feed and carriage return. */
            summary: string;
            /** @description Summaries in the window: at least one when ok, none when the window was empty. */
            task_count: number;
            /**
             * @description The window's length: always 24.
             * @constant
             */
            time_window_hours: 24;
            /**
             * @description The Worker sends only ok and empty_window.
             * @constant
             */
            status: "stale";
            /** @description Gemini model name; empty when no model was called. */
            model: string;
            /**
             * Format: date-time
             * @description When the report was computed.
             */
            computed_at: string;
            /**
             * Format: date-time
             * @description The window's start (exclusive): 24 hours before its end.
             */
            window_start: string;
            /**
             * Format: date-time
             * @description The window's end (inclusive): computed_at.
             */
            window_end: string;
        };
        /**
         * Todofy GET /api/recommendation response
         * @description Todofy GET /api/recommendation response: the ranked tasks the newsletter reads (it asks for ?top=10). tasks, model and task_count are the Go service's fields (handle_recommendation.go @ 6c46ed4); model is now a model name rather than a proto enum name, and unparsable model output is reported as status model_output_invalid with no tasks instead of being passed through as a fake task. Fields may be added, never removed or retyped, so consumers must ignore unknown fields. The limits are the newsletter's acceptance rules (newsletter src/newsletter/todofy.py _decode_recommendation), so any response that validates is one the newsletter accepts. Ranks are unique and at most top_n, which JSON Schema cannot express.
         */
        "recommendation-v1.schema": {
            /** @description Exactly what the Worker accepted from Gemini (JSON output constrained by the responseSchema from core/report_schema.py), ordered by rank. At most top_n items with ranks 1..top_n; fewer, even none, is valid and never padded. None when the window was empty or the model's output could not be used. */
            tasks: {
                /** @description Its rank, 1 first. */
                rank: number;
                /** @description Not blank; no control characters other than tab, line feed and carriage return. */
                title: string;
                /** @description Why it matters. Same rules as title. */
                reason: string;
            }[];
            /** @description Gemini model name; empty when no model was called. */
            model: string;
            /** @description Summaries the model saw: new_count + carryover_count (a rule cannot express the sum). At least one when ok, none when the window was empty. */
            task_count: number;
            /**
             * @description The newsletter endpoint sends only ok and empty_window; model_output_invalid appears only in stored copies the owner API lists.
             * @constant
             */
            status: "ok";
            /** @description How many tasks were asked for (the `top` query parameter, 1-10). */
            top_n: number;
            /**
             * Format: date-time
             * @description When the report was computed.
             */
            computed_at: string;
            /**
             * Format: date-time
             * @description The window's start (exclusive): 24 hours before its end.
             */
            window_start: string;
            /**
             * Format: date-time
             * @description The window's end (inclusive): computed_at.
             */
            window_end: string;
            /** @description Summaries of mail that arrived in the 24 h window (window_start, window_end]. Added 2026-09-30; absent from reports stored before. */
            new_count?: number;
            /** @description Older mail tasks (up to 14 days, at most 30) that the day's Todoist snapshot still lists as open, shown to the model as "[N 天前] summary"; 0 when no usable snapshot existed, and then the report is exactly the 24 h one. Added 2026-09-30; absent from reports stored before. */
            carryover_count?: number;
        } | {
            /** @description Exactly what the Worker accepted from Gemini (JSON output constrained by the responseSchema from core/report_schema.py), ordered by rank. At most top_n items with ranks 1..top_n; fewer, even none, is valid and never padded. None when the window was empty or the model's output could not be used. */
            tasks: {
                /** @description Its rank, 1 first. */
                rank: number;
                /** @description Not blank; no control characters other than tab, line feed and carriage return. */
                title: string;
                /** @description Why it matters. Same rules as title. */
                reason: string;
            }[];
            /** @description Gemini model name; empty when no model was called. */
            model: string;
            /**
             * @description Summaries the model saw: new_count + carryover_count (a rule cannot express the sum). At least one when ok, none when the window was empty.
             * @constant
             */
            task_count: 0;
            /**
             * @description The newsletter endpoint sends only ok and empty_window; model_output_invalid appears only in stored copies the owner API lists.
             * @constant
             */
            status: "empty_window";
            /** @description How many tasks were asked for (the `top` query parameter, 1-10). */
            top_n: number;
            /**
             * Format: date-time
             * @description When the report was computed.
             */
            computed_at: string;
            /**
             * Format: date-time
             * @description The window's start (exclusive): 24 hours before its end.
             */
            window_start: string;
            /**
             * Format: date-time
             * @description The window's end (inclusive): computed_at.
             */
            window_end: string;
            /** @description Summaries of mail that arrived in the 24 h window (window_start, window_end]. Added 2026-09-30; absent from reports stored before. */
            new_count?: number;
            /** @description Older mail tasks (up to 14 days, at most 30) that the day's Todoist snapshot still lists as open, shown to the model as "[N 天前] summary"; 0 when no usable snapshot existed, and then the report is exactly the 24 h one. Added 2026-09-30; absent from reports stored before. */
            carryover_count?: number;
        } | {
            /** @description Exactly what the Worker accepted from Gemini (JSON output constrained by the responseSchema from core/report_schema.py), ordered by rank. At most top_n items with ranks 1..top_n; fewer, even none, is valid and never padded. None when the window was empty or the model's output could not be used. */
            tasks: {
                /** @description Its rank, 1 first. */
                rank: number;
                /** @description Not blank; no control characters other than tab, line feed and carriage return. */
                title: string;
                /** @description Why it matters. Same rules as title. */
                reason: string;
            }[];
            /** @description Gemini model name; empty when no model was called. */
            model: string;
            /** @description Summaries the model saw: new_count + carryover_count (a rule cannot express the sum). At least one when ok, none when the window was empty. */
            task_count: number;
            /**
             * @description The newsletter endpoint sends only ok and empty_window; model_output_invalid appears only in stored copies the owner API lists.
             * @constant
             */
            status: "model_output_invalid";
            /** @description How many tasks were asked for (the `top` query parameter, 1-10). */
            top_n: number;
            /**
             * Format: date-time
             * @description When the report was computed.
             */
            computed_at: string;
            /**
             * Format: date-time
             * @description The window's start (exclusive): 24 hours before its end.
             */
            window_start: string;
            /**
             * Format: date-time
             * @description The window's end (inclusive): computed_at.
             */
            window_end: string;
            /** @description Summaries of mail that arrived in the 24 h window (window_start, window_end]. Added 2026-09-30; absent from reports stored before. */
            new_count?: number;
            /** @description Older mail tasks (up to 14 days, at most 30) that the day's Todoist snapshot still lists as open, shown to the model as "[N 天前] summary"; 0 when no usable snapshot existed, and then the report is exactly the 24 h one. Added 2026-09-30; absent from reports stored before. */
            carryover_count?: number;
        } | {
            /** @description Exactly what the Worker accepted from Gemini (JSON output constrained by the responseSchema from core/report_schema.py), ordered by rank. At most top_n items with ranks 1..top_n; fewer, even none, is valid and never padded. None when the window was empty or the model's output could not be used. */
            tasks: {
                /** @description Its rank, 1 first. */
                rank: number;
                /** @description Not blank; no control characters other than tab, line feed and carriage return. */
                title: string;
                /** @description Why it matters. Same rules as title. */
                reason: string;
            }[];
            /** @description Gemini model name; empty when no model was called. */
            model: string;
            /** @description Summaries the model saw: new_count + carryover_count (a rule cannot express the sum). At least one when ok, none when the window was empty. */
            task_count: number;
            /**
             * @description The newsletter endpoint sends only ok and empty_window; model_output_invalid appears only in stored copies the owner API lists.
             * @constant
             */
            status: "stale";
            /** @description How many tasks were asked for (the `top` query parameter, 1-10). */
            top_n: number;
            /**
             * Format: date-time
             * @description When the report was computed.
             */
            computed_at: string;
            /**
             * Format: date-time
             * @description The window's start (exclusive): 24 hours before its end.
             */
            window_start: string;
            /**
             * Format: date-time
             * @description The window's end (inclusive): computed_at.
             */
            window_end: string;
            /** @description Summaries of mail that arrived in the 24 h window (window_start, window_end]. Added 2026-09-30; absent from reports stored before. */
            new_count?: number;
            /** @description Older mail tasks (up to 14 days, at most 30) that the day's Todoist snapshot still lists as open, shown to the model as "[N 天前] summary"; 0 when no usable snapshot existed, and then the report is exactly the 24 h one. Added 2026-09-30; absent from reports stored before. */
            carryover_count?: number;
        };
        address: {
            address: string;
            name: string;
        } & {
            [key: string]: unknown;
        };
        attachment: {
            filename: string;
            content_type: string;
            size: number;
            /**
             * @description Copy status at event creation, not a promise of perpetual availability.
             * @enum {unknown}
             */
            storage_status?: "stored" | "omitted";
            /** @enum {unknown} */
            omitted_reason?: "size_limit" | "message_size_limit" | "inline_image" | "capacity";
        } & {
            [key: string]: unknown;
        };
        /** Mail Hero mail.received.v1 event */
        "mail-received-v1.schema": {
            /** @constant */
            type: "mail.received.v1";
            /** Format: uuid */
            event_id: string;
            /** Format: date-time */
            received_at: string;
            /** @description Present only on synthetic end-to-end canary events (contracts/ops-v1). Consumers MUST NOT cause external side effects (tasks, messages, reports) for an event that carries it. An event whose canary is present but unreadable must not cause side effects either: reject it (4xx) or handle it as a canary. */
            canary?: {
                run_id: string;
            } & {
                [key: string]: unknown;
            };
            message: (({
                /** Format: uuid */
                id: string;
                from: components["schemas"]["address"][];
                to: components["schemas"]["address"][];
                subject: string;
                /** Format: date-time */
                sent_at: string | null;
                rfc_message_id: string | null;
                text: string;
                text_truncated?: boolean;
                /** @description UTF-8 size of normalized plaintext before UI/webhook truncation; not raw MIME size. */
                original_text_bytes?: number;
                html_omitted?: boolean;
                needs_review?: boolean;
                warnings?: string[];
                content_policy_version?: string;
                /** @description Attachment records omitted beyond the 100-record metadata cap. Excludes listed records whose byte copies were omitted. */
                attachments_omitted_count?: number;
                attachments: components["schemas"]["attachment"][];
            } & {
                [key: string]: unknown;
            }) & unknown) | {
                subject?: unknown;
            } | {
                text?: unknown;
            };
            $defs: {
                address: {
                    address: string;
                    name: string;
                } & {
                    [key: string]: unknown;
                };
                attachment: {
                    filename: string;
                    content_type: string;
                    size: number;
                    /**
                     * @description Copy status at event creation, not a promise of perpetual availability.
                     * @enum {unknown}
                     */
                    storage_status?: "stored" | "omitted";
                    /** @enum {unknown} */
                    omitted_reason?: "size_limit" | "message_size_limit" | "inline_image" | "capacity";
                } & {
                    [key: string]: unknown;
                };
            };
        } & {
            [key: string]: unknown;
        };
    };
    responses: {
        /** @description `invalid_request` (query or body) or `invalid_payload` (webhook contract or Idempotency-Key). */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `unauthorized`: missing or invalid Access JWT, Bearer token or Basic credentials. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `csrf_failed`: wrong Origin, or missing or invalid CSRF token. Fetch a new token and retry. */
        CsrfFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `not_found`. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `event_conflict`, `version_conflict`, `action_not_allowed` or `action_request_conflict`. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `payload_too_large`: over 1 MiB. */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `unsupported_media_type`: not application/json. */
        UnsupportedMediaType: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `rate_limited`. */
        TooManyRequests: {
            headers: {
                "Retry-After": components["headers"]["RetryAfter"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `maintenance`, `not_configured`, `access_not_configured` or `unavailable` (D1, the coordinator or a needed report is unavailable). */
        Unavailable: {
            headers: {
                "Retry-After": components["headers"]["RetryAfter"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        EventId: components["schemas"]["EventId"];
        /** @description Opaque `next_cursor` from the previous page. */
        Cursor: string;
        Limit: number;
    };
    requestBodies: never;
    headers: {
        /** @description Seconds to wait before retrying. */
        RetryAfter: number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCsrfToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The token to send as `X-CSRF-Token`; valid for 12 hours. */
            200: {
                headers: {
                    /** @description `todofy_csrf=<token>; Path=/; HttpOnly; SameSite=Strict; Secure; Max-Age=43200` */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Csrf"];
                };
            };
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["Unavailable"];
        };
    };
    getOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current overview. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["Unavailable"];
        };
    };
    listEvents: {
        parameters: {
            query?: {
                view?: "recent" | "attention";
                /** @description Only with view=recent; combining it with view=attention is 400 `invalid_request`. */
                state?: components["schemas"]["EventState"];
                /** @description Opaque `next_cursor` from the previous page. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of events. Never includes mail content. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["Unavailable"];
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The event. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["Unavailable"];
        };
    };
    reconcileEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: components["parameters"]["EventId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReconcileRequest"];
            };
        };
        responses: {
            /** @description The event after the transition. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["CsrfFailed"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["Unavailable"];
        };
    };
    listReminders: {
        parameters: {
            query?: {
                /** @description Opaque `next_cursor` from the previous page. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of reminders. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReminderPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["Unavailable"];
        };
    };
    getLatestReports: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest reports. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportsLatest"];
                };
            };
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["Unavailable"];
        };
    };
    recomputeReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecomputeRequest"];
            };
        };
        responses: {
            /** @description The stored report. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["summary-v1.schema"] | components["schemas"]["recommendation-v1.schema"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["CsrfFailed"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["Unavailable"];
        };
    };
    getDailyMetrics: {
        parameters: {
            query?: {
                /** @description How many finished days to return. */
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One entry per day. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyMetrics"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["Unavailable"];
        };
    };
    getGtdDaily: {
        parameters: {
            query?: {
                /** @description How many UTC days, ending today. */
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One entry per day, and the latest review week. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GtdDaily"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["Unavailable"];
        };
    };
    getLegacyText: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A ledger event ID, or `legacy:<hash>` / `legacy:row-<id>` for an imported cache row with no ledger event (CloudMailin era, or an unlinked Mail Hero row). Those rows are an archive; no endpoint lists them, so their IDs come from D1 (`wrangler d1 execute`). */
                event_id: components["schemas"]["EventId"] | string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The text. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LegacyText"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["Unavailable"];
        };
    };
    getSetup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Setup facts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Setup"];
                };
            };
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["Unavailable"];
        };
    };
    receiveMail: {
        parameters: {
            query?: never;
            header: {
                /** @description Exactly one header, byte-equal to the body's `event_id`; otherwise 400. */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        /**
         * @description At most 1 MiB. A declared `Content-Length` over 1 MiB is 413 before the body is read;
         *     without `Content-Length` the body is read up to 1 MiB and anything longer is 413.
         */
        requestBody: {
            content: {
                "application/json": components["schemas"]["mail-received-v1.schema"];
            };
        };
        responses: {
            /** @description Stored */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            503: components["responses"]["Unavailable"];
        };
    };
    getDailySummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The summary computed since the latest precompute time (REPORT_PRECOMPUTE_UTC), or computed on demand; any other case is 503, never an older report. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["summary-v1.schema"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["Unavailable"];
        };
    };
    getRecommendation: {
        parameters: {
            query?: {
                /** @description Absent or empty means 3. Like the Go service, a sign and leading zeros are accepted. */
                top?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The recommendation for `top` computed since the latest precompute time, or computed on demand; any other case (including unusable model output) is 503, never an older or empty-by-failure report. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["recommendation-v1.schema"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["Unavailable"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Worker is serving. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
