// Generates src/api/schema.d.ts from the OpenAPI contract; --check fails when the
// committed file differs, so the UI types cannot drift from the Worker's contract.
import { readFile, writeFile } from 'node:fs/promises'
import openapiTS, { astToString } from 'openapi-typescript'

const source = new URL('../../api/owner-api-v1.openapi.yaml', import.meta.url)
const target = new URL('../src/api/schema.d.ts', import.meta.url)
const header = '// Generated by `npm run gen:api` from api/owner-api-v1.openapi.yaml. Do not edit.\n\n'

const generated = header + astToString(await openapiTS(source))

if (process.argv.includes('--check')) {
  const committed = await readFile(target, 'utf8').catch(() => '')
  if (committed !== generated) {
    console.error(
      'src/api/schema.d.ts is out of date with api/owner-api-v1.openapi.yaml or a schema it $refs ' +
        '(api/*-v1.schema.json, generated from proto/todofy/report/v1); run `npm run gen:api`.',
    )
    process.exit(1)
  }
  console.log('src/api/schema.d.ts matches the OpenAPI contract.')
} else {
  await writeFile(target, generated)
  console.log('Wrote src/api/schema.d.ts')
}
