#!/usr/bin/env python3
"""Materialize public identities into the existing sole production configs."""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import tempfile
from pathlib import Path, PurePosixPath

from cloud_profile import ProfileError, load_profile, load_resources, read_public, require

REPO = Path(__file__).resolve().parents[2]
IDENTITY_MODULE = "dashboard/worker/src/resource-identities.ts"
PLATFORM_IDENTITY = "infra/platform-identity.tf"


def literal_field(text: str, name: str, value: str, section: str | None = None) -> str:
    """Replace one quoted field only; preserve comments and all unrelated bytes."""
    start, end = 0, len(text)
    if section is not None:
        blocks = list(re.finditer(r"(?m)^\[\[?([^\]\n]+)\]\]?[ \t]*(?:#.*)?$", text))
        found = [(index, match) for index, match in enumerate(blocks)
                 if match.group(1) == section and not match.group(0).startswith("[[")]
        require(len(found) == 1, "config section " + section)
        index, match = found[0]
        start = match.end()
        end = blocks[index + 1].start() if index + 1 < len(blocks) else len(text)
    else:
        first = re.search(r"(?m)^\[", text)
        end = first.start() if first else len(text)
    body = text[start:end]
    pattern = re.compile(r"(?m)^(" + re.escape(name) + r'\s*=\s*)"[^"\n]*"(?=\s*(?:#.*)?$)')
    require(len(pattern.findall(body)) == 1, "config field " + name)
    body = pattern.sub(lambda match: match.group(1) + json.dumps(value), body)
    return text[:start] + body + text[end:]


def d1_fields(text: str, resources: dict) -> str:
    pattern = re.compile(r"(?ms)^\[\[d1_databases\]\][^\n]*\n(.*?)(?=^\[|\Z)")
    def replace(match):
        body = match.group(1)
        names = re.findall(r'^database_name\s*=\s*"([^"\n]+)"', body, re.M)
        require(len(names) == 1 and names[0] in resources["d1_databases"], "D1 identity coverage")
        replacement = literal_field(body, "database_id", resources["d1_databases"][names[0]])
        return match.group(0)[:len(match.group(0)) - len(body)] + replacement
    return pattern.sub(replace, text)


def config_paths(root: Path) -> list[str]:
    result = []
    for manifest in sorted(root.glob("*/app.toml")):
        data = read_public(manifest)
        for worker in data.get("workers", []):
            relative = worker.get("config")
            require(isinstance(relative, str), "production config path")
            path = PurePosixPath(relative)
            require(not path.is_absolute() and path.parts[0] == manifest.parent.name
                    and path.name == "wrangler.toml" and "\\" not in relative
                    and all(part and not part.startswith(".") for part in relative.split("/")),
                    "production config path")
            require(relative not in result, "production config path")
            result.append(relative)
    require(bool(result), "production config coverage")
    return result


def identity_module(profile: dict, resources: dict) -> str:
    matches = {name + "-db": value for name, value in resources["d1_databases"].items()}
    require(not set(matches) & set(resources["durable_objects"]), "resource identity overlap")
    matches.update(resources["durable_objects"])
    rows = "\n".join("  " + json.dumps(name) + ": " + json.dumps(value) + "," for name, value in sorted(matches.items()))
    return ("// Generated by tools/cloud-config/generate.py; public resource identifiers only.\n"
            "// Never imported by the UI or served by the public registry.\n"
            "export const OWNER_ZONE = " + json.dumps(profile["zone"]) + ";\n"
            "export const RESOURCE_IDENTITIES: Readonly<Record<string, string | null>> = {\n" + rows + "\n};\n")


def platform_identity(profile: dict, resources: dict) -> str:
    """Public DNS identity only; account credentials remain Terraform variables."""
    values = {"platform_zone_id": resources["zone_id"], "platform_zone": profile["zone"],
              "fleet_hostname": profile["platform_hostname"],
              "platform_runtime_hostname": profile["vps"]["platform_runtime_host"],
              "platform_access_team": profile["access_issuer"].removeprefix("https://").removesuffix(".cloudflareaccess.com")}
    width = max(map(len, values))
    rows = "\n".join("  " + name.ljust(width) + " = " + json.dumps(value) for name, value in values.items())
    return ("# Generated by tools/cloud-config/generate.py; public DNS identity only.\n"
            "# Account credentials and private values remain sensitive Terraform variables.\n"
            "locals {\n" + rows + "\n}\n")


def generated_files(root: Path) -> dict[str, str]:
    profile, resources = load_profile(root), load_resources(root)
    outputs = {}
    used_audiences, used_databases = set(), set()
    for relative in config_paths(root):
        path = root / relative
        config = read_public(path)
        require("env" not in config and "keep_vars" not in config, "sole production config")
        name = config.get("name")
        require(isinstance(name, str), "Worker name")
        text = literal_field(path.read_text(encoding="utf-8"), "account_id", resources["account_id"])
        variables = config.get("vars", {})
        if "ACCOUNT_ID" in variables:
            text = literal_field(text, "ACCOUNT_ID", resources["account_id"], "vars")
        if "ACCESS_ISSUER" in variables:
            text = literal_field(text, "ACCESS_ISSUER", profile["access_issuer"], "vars")
        if "ACCESS_AUDIENCE" in variables:
            require(name in resources["access_audiences"], "Access audience coverage")
            used_audiences.add(name)
            text = literal_field(text, "ACCESS_AUDIENCE", resources["access_audiences"][name], "vars")
        if name == "fleet":
            text = literal_field(text, "HOST_KEY", profile["vps"]["observer_node_key"], "vars")
        for database in config.get("d1_databases", []):
            used_databases.add(database.get("database_name"))
        text = d1_fields(text, resources)
        outputs[relative] = text
    require(used_audiences == set(resources["access_audiences"]), "Access audience coverage")
    require(used_databases == set(resources["d1_databases"]), "D1 identity coverage")
    outputs[IDENTITY_MODULE] = identity_module(profile, resources)
    outputs[PLATFORM_IDENTITY] = platform_identity(profile, resources)
    return outputs


def check(root: Path, outputs: dict[str, str]) -> list[str]:
    return [relative for relative, text in outputs.items()
            if not (root / relative).is_file() or (root / relative).is_symlink()
            or (root / relative).read_text(encoding="utf-8") != text]


def write(root: Path, outputs: dict[str, str]) -> list[str]:
    stale = check(root, outputs)
    for relative in stale:
        path = root / relative
        require(not path.is_symlink() and not any(parent.is_symlink() for parent in path.parents), relative)
        require(path.parent.is_dir(), relative)
        fd, temporary = tempfile.mkstemp(prefix=".cloud-config-", dir=path.parent)
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as handle:
                handle.write(outputs[relative])
            os.chmod(temporary, path.stat().st_mode & 0o777 if path.exists() else 0o644)
            os.replace(temporary, path)
        finally:
            if os.path.exists(temporary):
                os.unlink(temporary)
    return stale


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Reject stale files without writing")
    args = parser.parse_args(argv)
    try:
        outputs = generated_files(REPO)
        stale = check(REPO, outputs)
        if args.check and stale:
            print("Cloud configuration is stale: " + ", ".join(stale), file=sys.stderr)
            return 1
        if not args.check:
            write(REPO, outputs)
        print("Cloud configuration: " + ("checked" if args.check else "generated") + f" {len(outputs)} files")
        return 0
    except (ProfileError, OSError) as error:
        print(str(error) if isinstance(error, ProfileError) else "Cannot access cloud configuration files", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
